### ISSUE TITLE
Linux服务器Elasticsearch集群安装

### ISSUE THREAD

**Issue by lijqh** [lijqh/notes#1]
Elasticsearch是一款优秀的全文搜索引擎，提供基于RESTful web接口，是当前流行的企业级搜索引擎。可以用于大型云计算平台，提供实时搜索服务，也可以用于基于检索的聊天机器人，提供知识库的索引功能。

本文介绍在多台服务器中部署Elasticsearch集群，单台服务器部署也可以采用同样步骤，配置稍微有一点区别（文中会提到）。先到Elasticsearch官方网站上下载最新安装包。本文以6.2.4版本为例。
1、创建用户
```
 groupadd elastic
 useradd elastic -g elastic
 mkdir /opt/elastic
 chown -R elastic:elastic /opt/elastic 
```

安装包上传至Linux服务器/home/elastic目录下。
2、安装Java（如已有不需安装，Java 8）
```
 mkdir /usr/java/
 tar -zxvf /home/elastic/jdk-8u171-linux-x64.tar.gz -C /usr/java/ 
```

3、修改环境变量
` vi /etc/profile `

末尾添加
```
 export JAVA_HOME=/usr/java/jdk1.8.0_171
 export JRE_HOME=${JAVA_HOME}/jre
 export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
 export PATH=${JAVA_HOME}/bin:$PATH 
```

 保存退出执行 
` source /etc/profile `

4、安装ES
root用户下，给elastic用户指定密码，切换至elastic用户，安装ES
```
 passwd elastic
 su elastic
 cd /home/elastic
 tar -zxvf elasticsearch-6.2.4.tar.gz -C /opt/elastic/ 
```

5、配置ES
 exit #退出elastic用户回到root
```
 mkdir -p /var/elasticsearch/data
 mkdir -p /var/elasticsearch/logs
 chown -R elastic:elastic /var/elasticsearch
 su elastic
 cd /opt/elastic/elasticsearch-6.2.4/
 vi config/elasticsearch.yml 
```

以下为Elasticsearch配置文件的一个示例：（如果你有多台Linux服务器，修改相应ip和discovery.zen.minimum_master_nodes即可，如果只有一台服务器，discovery.zen那两行注释掉即可）
```yaml
#======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ————————————————— Cluster —————————————————
#
# Use a descriptive name for your cluster:
#
cluster.name: ES_Cluster
node.master: true
node.data: true

#
# —————————————————— Node ——————————————————
#
# Use a descriptive name for the node:
#
node.name: “ES1”
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ————————————————— Paths ——————————————————
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/elasticsearch/data
#
# Path to log files:
#
path.logs: /var/elasticsearch/logs
#
# ————————————————— Memory —————————————————
#
# Lock the memory on startup:
#
bootstrap.memory_lock: false
bootstrap.system_call_filter: false

#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ————————————————— Network —————————————————
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# ———————————————— Discovery —————————————————
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is [“127.0.0.1”, “[::1]”]
#
discovery.zen.ping.unicast.hosts: [“192.168.0.1”, “192.168.0.2”, “192.168.0.3”]
#
# Prevent the “split brain” by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
discovery.zen.minimum_master_nodes: 2
#
# For more information, consult the zen discovery module documentation.
#
# ————————————————— Gateway —————————————————
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ————————————————— Various —————————————————
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
```

 其中，discovery.zen.minimum_master_nodes的设置原则为: (候选主节点数/2+1)
6、JVM配置
在生产环境PRD中安装Elasticsearch还需要修改一下Elasticsearch使用的堆空间大小（heap size），这个配置在elasticsearch安装目录/config/jvm.options中，例如：
` vi /opt/elastic/elasticsearch-6.2.4/config/jvm.options`

修改下面两行，也可先保持默认，分别将最小/最大堆空间设为20g：
```
 -Xms20g
 -Xmx20g 
```

这个空间大小的设置取决于服务器内存的大小，需要注意以下几点：
通常将Xms（最小）设置为与Xmx（最大）值相同
堆空间越大Elasticsearch可以使用的缓存越大，但也将花费越多的垃圾回收时间
通常将Xmx设为不超过内存的50%，以保证留有足够的物理内存空间给系统缓存
参考【官方文档】 ：
7、修改系统配置
切换至root
` vi /etc/security/limits.conf`

增加以下内容：
```
 * soft nofile 65536
 * hard nofile 131072
 * soft nproc 4096
 * hard nproc 4096
 * soft memlock unlimited
 * hard memlock unlimited 
```

重要：必须做以下修改
```
 cp /etc/security/limits.d/90-nproc.conf /etc/security/limits.d/90-nproc.conf_bak
 vi /etc/security/limits.d/90-nproc.conf 
```

添加上述同样内容
```
 * soft nofile 65536
 * hard nofile 131072
 * soft nproc 4096
 * hard nproc 4096
 * soft memlock unlimited
 * hard memlock unlimited 
```

重新登录root帐号使配置生效
打开文件/etc/sysctl.conf，增加：
` vm.max_map_count=262144 `

运行下述命令使配置生效
` sudo sysctl -p /etc/sysctl.conf `

使用以上步骤对其他服务器进行同样的操作
8、启动elasticsearch
切换至用户elastic
```
 cd /opt/elastic/elasticsearch-6.2.4/bin
 ./elasticsearch -d 
```

在浏览器中输入地址http://xxx.xxx.xxx.xx1:9200，查看启动状态，出现如下内容表示ES启动成功：
```
 {
  "name" : "xxx.xxx.xxx.xx1",
  "cluster_name" : "ES_CLUSTER",
  "cluster_uuid" : "xxxxxxxxxxxxxxxxxxxxx",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "xxxxxxxxxxxx",
    "build_date" : "xxxxxxxxxxxxxxxxxxxxx",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

9、安装Kibana
elastic用户下，安装包kibana-6.2.4-linux-x86_64.tar.gz放入/home/elastic
```
 cd /home/elastic
 tar –zxvf kibana-6.2.4-linux-x86_64.tar.gz -C /opt/elastic/ 
```

修改配置文件/kibana-6.2.4-linux-x86_64/config/kibana.yml，修改如下内容：
```
# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "xxx.xxx.xxx.xx1"

# The URL of the Elasticsearch instance to use for all your queries.
elasticsearch.url: "http://xxx.xxx.xxx.xx1:9200"
```

后台启动Kibana
` nohup ./kibana & `

在浏览器中输入 http://xxx.xxx.xxx.xx1:5601，测试
参考文档
Set up Elasticsearch | Elasticsearch Reference [6.2] | Elastic
